### ISSUE TITLE
SIP MESSAGE from messenger successfully reaches olympus but no 200 OK is returned to messenger

### ISSUE THREAD

**Issue by atsakiridis** [Mobicents/restcomm-ios-sdk#241]
Scenario

- Messenger sends SIP MESSAGE to olympus (via Restcomm)
- Olympus receives message correctly and responds 200 OK to Restcomm
- No 200 OK is sent back from Restcomm to messenger

IMPORTANT: Scenario is not always reproducible, but usually 1/2 times.

Checking Restcomm logs shows that Restcomm gets an NPE before managing to send the response:

09:33:05,411 ERROR [org.mobicents.servlet.restcomm.sms.SmsService] (RestComm-akka.actor.default-dispatcher-96753) null: java.lang.NullPointerException
	at org.mobicents.servlet.restcomm.sms.SmsService.response(SmsService.java:345) [restcomm.sms-7.3.1.1157.jar:]
	at org.mobicents.servlet.restcomm.sms.SmsService.onReceive(SmsService.java:330) [restcomm.sms-7.3.1.1157.jar:]
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:159) [akka-actor_2.10-2.1.2.jar:]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425) [akka-actor_2.10-2.1.2.jar:]
	at akka.actor.ActorCell.invoke(ActorCell.scala:386) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.Mailbox.run(Mailbox.scala:212) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506) [akka-actor_2.10-2.1.2.jar:]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) [scala-library-2.10.1.jar:]

Full Restcomm logs at:

https://gist.github.com/atsakiridis/0aa56a7e50a32868bde1

**Comment by gvagenas** [comment]
@atsakiridis I have prepared a patch for issue https://github.com/Mobicents/restcomm-ios-sdk/issues/240 (Restcomm: https://github.com/Mobicents/RestComm/issues/442) which I believe solves this issue. Please try again when new binary will be ready and if problem persists provide me full log and tcpdump for the case

**Comment by atsakiridis** [comment]
@gvagenas even though the other message issue is fixed, this issue still occurs. I re-collected logs and cap and placed them here:

capture: https://drive.google.com/file/d/0BwfD74mG87iMSnQ5Y2hKMWp1LUk/view?usp=sharing
full restcomm log: https://drive.google.com/file/d/0BwfD74mG87iMdy1nLTRHeTlCSFU/view?usp=sharing

If you want just the log excerpt of the scenario, you can check: https://gist.github.com/atsakiridis/0aa56a7e50a32868bde1

I have updated it

**Comment by atsakiridis** [comment]
This is a restcomm issue, but I'll keep it open on iOS as well to remember to verify on next release

**Comment by atsakiridis** [comment]
This is still occuring, opened https://github.com/Mobicents/RestComm/issues/691
